version: '3'

services:
  activemq:
    image: masstransit/activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    ports:
      - "8161:8161"
      - "61616:61616"
